### ISSUE TITLE
fbx format convert fail

### ISSUE THREAD

**Issue by clime57** [wangerzi/3d-model-convert-to-gltf#12]
1.GRPC Mode:

use command line to start in windows:

docker pull wj2015/3d-model-convert-to-gltf:latest
docker run -d -p 8999:8999 wj2015/3d-model-convert-to-gltf:latest

all success except fbx.

2.command line mode log:

D:\3d-model-convert-to-gltf\server\examples\python>docker run -v D:\3d-model-convert-to-gltf\assets:/assets wj2015/3d-model-convert-to-gltf:latest /bin/bash -c "cd /assets && conda run -n pythonocc python /opt/3d-model-convert-to-gltf/server/convert.py fbx Samba_Dancing.fbx test.glb"
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '/opt/3d-model-convert-to-gltf/server/convert.py', 'fbx', 'Samba_Dancing.fbx', 'test.glb']' command failed.  (See above for error)
Traceback (most recent call last):
  File "/opt/3d-model-convert-to-gltf/server/convert.py", line 33, in <module>
    main()
  File "/opt/3d-model-convert-to-gltf/server/convert.py", line 20, in main
    out_convert_gltf_path = Convert.convert_by_type(sys.argv[1], os.path.abspath(sys.argv[2]), is_bin)
  File "/opt/3d-model-convert-to-gltf/server/service/Convert.py", line 219, in convert_by_type
    result = model.handler(file_path, is_bin)
TypeError: handler() missing 1 required positional argument: 'need_draco'

**Comment by clime57** [comment]
v1.5 mirror file is good.v1.6 and latest have this bug

**Comment by wangerzi** [comment]
Thanks for your clearly feedback, the error seems like `convert.py` params pass problem, I'm already fixed but forget to push image before.

I will remind you again after this problem solved.

https://github.com/wangerzi/3d-model-convert-to-gltf/blob/master/server/service/Convert.py#L178
