### ISSUE TITLE
FBX文件转换失败的原因未知？如何解决

### ISSUE THREAD

**Issue by SHMay100G** [wangerzi/3d-model-convert-to-gltf#18]
(base) bash-5.1# conda run -n pythonocc python /opt/3d-model-convert-to-gltf/server/convert.py fbx /opt/3d-model-convert-to-gltf/assets/Samba_Dancing.fbx /opt/out_test.glb no-draco
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '/opt/3d-model-convert-to-gltf/server/convert.py', 'fbx', '/opt/3d-model-convert-to-gltf/assets/Samba_Dancing.fbx', '/opt/out_test.glb', 'no-draco']' command failed.  (See above for error)
True False

fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
fbx2gltf: /usr/lib/libstdc++.so.6: no version information available (required by fbx2gltf)
Traceback (most recent call last):
  File "/opt/3d-model-convert-to-gltf/server/convert.py", line 36, in <module>
    main()
  File "/opt/3d-model-convert-to-gltf/server/convert.py", line 23, in main
    out_convert_gltf_path = Convert.convert_by_type(sys.argv[1], os.path.abspath(sys.argv[2]), is_bin, need_draco)
  File "/opt/3d-model-convert-to-gltf/server/service/Convert.py", line 220, in convert_by_type
    result = model.handler(file_path, is_bin, need_draco)
  File "/opt/3d-model-convert-to-gltf/server/service/Convert.py", line 186, in handler
    raise ConvertException('fbx convert draco gltf fail, file:' + convert_gltf_path)
exception.ConvertException.ConvertException: fbx convert draco gltf fail, file:/opt/3d-model-convert-to-gltf/assets/Samba_Dancing.fbx.glb

**Comment by Fine974** [comment]
请问你解决了这个问题吗，我也遇到了同样的问题
